[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hatch_project"
version = "0.1.0"
description = "Common dependencies and shared code for the monorepo"
dependencies = [
    "numpy",
    "pandas"
]
